spring:
  application:
    name: mytasknote-api
  datasource:
    url: jdbc:mysql://localhost:3309/mytasknote?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: appuser
    password: apppass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
# Secrets Manager 設定
aws:
  region: ap-northeast-1
  secrets:
    dbSecretName: mytasknote/db/aurora
management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
server:
  port: 8080
security:
  jwt:
    secret: "change-this-to-long-random-string-32chars-minimum"
    expiration-ms: 3600000  # 1時間